vim.wo.number = true
-- vim.o.relativenumber = true -- Set relative numbered lines
vim.o.clipboard = 'unnamedplus' -- Sync clipboard btwn OS and Neovim. (default: '')
vim.o.wrap = false -- Display line as one long line (default: true)
vim.o.linebreak = true -- companion to wrap. Don't split words
vim.o.mouse = 'a' -- Enable mouse mode. (default: '')
vim.o.autoindent = true
vim.o.smartindent = true --Make indenting smarter
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.shiftwidth = 4 -- The number of spaces inserted for each indetation (default: 8)
vim.o.tabstop = 4 --Insert n spaces for a tab (default: 8)
vim.o.softtabstop = 4
vim.o.expandtab = true
vim.o.scrolloff = 4
vim.o.sidescrolloff = 8
vim.o.cursorline = false
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.hlsearch = false
vim.o.showmode = false
vim.o.whichwrap = 'bs<>[]hl'
vim.o.numberwidth = 4
vim.o.swapfile = false -- Create a swappfile (default: true)
vim.o.showtabline = 2 -- Always show tabs (default: 1)
vim.o.backspace = 'indent,eol,start' -- Allow backspace on (default: 'indent,eol,start')
vim.o.pumheight = 10 -- Pop up menu height (default: 0)
vim.o.conceallevel = 0 -- So that `` is invisible on markdown
vim.o.fileencoding = 'utf-8'
vim.o.cmdheight = 2
vim.opt.termguicolors = true

